### ISSUE TITLE
Catch duplicated names in images

### ISSUE THREAD

**Issue by giosava94** [infn-datacloud/federation-registry-feeder#33]
Lo script ha lanciato e non ha catturato il seguente errore:
```
Traceback (most recent call last):
  File "/app/src/main.py", line 85, in <module>
    main(args.loglevel.upper())
  File "/app/src/main.py", line 46, in main
    providers_data = list(providers_data)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/main.py", line 45, in <lambda>
    providers_data = executor.map(lambda x: x.get_provider(), pthreads)
                                            ^^^^^^^^^^^^^^^^
  File "/app/src/providers/core.py", line 147, in get_provider
    provider_data = list(provider_data)
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/providers/core.py", line 56, in retrieve_data
    return item.get_provider_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/providers/conn_thread.py", line 55, in get_provider_data
    return OpenstackData(
           ^^^^^^^^^^^^^^
  File "/app/src/providers/openstack.py", line 86, in __init__
    self.retrieve_info()
  File "/app/src/providers/openstack.py", line 109, in retrieve_info
    srv = self.get_compute_service()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/providers/openstack.py", line 479, in get_compute_service
    compute_service.images = self.get_images(tags=self.provider_conf.image_tags)
    ^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 384, in pydantic.main.BaseModel.__setattr__
pydantic.error_wrappers.ValidationError: 1 validation error for ComputeServiceCreateExtended
images
  There are multiple items with identical name: cirros (type=assertion_error)
```

**Comment by giosava94** [comment]
Resolved in #34
